APICanalLuciernaga/APICanalLuciernaga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from APICanalLuciernaga import settings
from django.contrib.flatpages import views
from rest_framework import routers
from biblioteca.views import BibliotecaViewSet, CategoriaBibliotecaViewSet
from programacion.views import HoraProgramacionViewSet
from noticias.views import ComunicacionViewSet, CategoriaNoticiaViewSet
from videoteca.views import VideoViewSet, EpisodioViewSet,TipoVideoTecaViewSet, CategoriaVideoTecaViewSet
from lugar.views import PaisViewSet

router = routers.DefaultRouter()
router.register('biblioteca', BibliotecaViewSet)
router.register('programacion', HoraProgramacionViewSet)
router.register('noticia', ComunicacionViewSet)
router.register('videoteca', VideoViewSet)
router.register('episodio', EpisodioViewSet)
router.register('categoria-noticia', CategoriaNoticiaViewSet)
# router.register('clasficacion-noticia', ClasificacionNoticiaViewSet)
router.register('categoria-video', CategoriaVideoTecaViewSet)
router.register('tipo-videoteca', TipoVideoTecaViewSet)
router.register('pais', PaisViewSet)
router.register('categoria-biblioteca', CategoriaBibliotecaViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('api/v1/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('acerca/', views.flatpage, {'url': '/acerca/'}, name='acerca'),
    path('',include('noticias.urls')),
    path('videos/',include('videoteca.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('en-directo/',include('programacion.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )
    
urlpatterns += staticfiles_urlpatterns()

APICanalLuciernaga/biblioteca/urls.py
from django.urls import path
from .views import Biblioteca_list

urlpatterns = [
	path('',Biblioteca_list,name='biblioteca_list'),
]

APICanalLuciernaga/noticias/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('',home,name='home'),
	path('noticias/',news,name='news'),
	path('noticias/detalles/<slug>/',news_detail,name='news_detail'),
]

APICanalLuciernaga/biblioteca/models.py
from django.db import models
from sorl.thumbnail import ImageField
from noticias.models import Categoria
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Biblioteca(models.Model):
    nombre = models.CharField(max_length = 225)
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    descripcion = RichTextUploadingField(verbose_name='Descripción')
    foto = ImageField('Imagen',upload_to='fotos/biblioteca')
    archivo = models.FileField(upload_to='documento/biblioteca')

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = "Biblioteca"
        verbose_name_plural = "Biblioteca"

APICanalLuciernaga/programacion/models.py
from django.db import models
from noticias.models import Categoria

# Create your models here.
class Programacion(models.Model):
	titulo = models.CharField(max_length = 225)
	link = models.URLField(null=True,blank=True)
	fecha = models.DateField()

	def __str__(self):
		return self.titulo
	
	class Meta:
		verbose_name = "Programación"
		verbose_name_plural = "Programaciones"

class HoraProgramacion(models.Model):
	programacion = models.ForeignKey(Programacion, on_delete = models.CASCADE)
	titulo = models.CharField(max_length = 225)
	categoria_p = models.ForeignKey(Categoria,on_delete=models.DO_NOTHING,null=True,verbose_name='Categoría')
	descripcion = models.CharField("Descripción", max_length=200, blank=True, null=True)
	hora_inicio = models.TimeField()
	hora_fin = models.TimeField()

	class Meta:
		verbose_name ="Hora Programación"
		verbose_name_plural ="Horas de programacion"

	def __str__(self):
		return self.titulo
		
	

APICanalLuciernaga/videoteca/models.py
from django.db import models
from django.utils.text import slugify
from lugar.models import Pais
from sorl.thumbnail import ImageField
from noticias.models import Categoria
from ckeditor_uploader.fields import RichTextUploadingField

#Create your models here.

class Tipo(models.Model):
    nombre = models.CharField(max_length = 255)
    
    class Meta:
         ordering = ['-id']

    def __str__(self):
        return self.nombre


class Director(models.Model):
    nombre = models.CharField(max_length = 255)
    fecha_nacimiento = models.DateField('Fecha de nacimiento')

    def __str__(self):
        return self.nombre
    
    class Meta: 
        verbose_name = "Director"
        verbose_name_plural = "Directores"
        ordering = ['-id']


class Video(models.Model):
    tipo = models.ForeignKey(Tipo,on_delete=models.CASCADE)
    portada = models.BooleanField('Portada',default=False)
    categoria = models.ManyToManyField(Categoria,verbose_name='Categoría')
    nombre = models.CharField('Nombre',max_length = 225)
    imagen = ImageField('Imagen',upload_to='fotos/videos')
    sinopsis = RichTextUploadingField(verbose_name='Descripción')
    fecha = models.DateField('Fecha') 
    director = models.ForeignKey(Director, on_delete = models.CASCADE,verbose_name='Director')
    produccion = models.CharField('Producción',max_length = 255)
    pais = models.ForeignKey(Pais, on_delete = models.CASCADE,verbose_name='País')
    duracion = models.CharField('Duración',max_length=20)
    url = models.URLField(null = True, blank = True)
    slug = models.SlugField(max_length = 250, unique=True, editable= False)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = "Video"
        verbose_name_plural = "Videos"
        ordering = ['-id']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        super(Video, self).save(*args, **kwargs)

TEMPORADAS_CHOICE = [
    (1, 'Temporada 1'),
    (2, 'Temporada 2'),
    (3, 'Temporada 3'),
    (4, 'Temporada 4'),
    (5, 'Temporada 5'),
]

class Temporada(models.Model):
    info_video = models.ForeignKey(Video, on_delete = models.CASCADE)
    temporada = models.IntegerField(choices = TEMPORADAS_CHOICE)

    class Meta:
        verbose_name = "Temporada"
        verbose_name_plural = "Temporadas"

class Episodio(models.Model):
    temporada = models.ForeignKey(Temporada, on_delete = models.CASCADE)
    link = models.URLField(max_length = 225)
    imagen = ImageField('Imagen',upload_to='fotos/videos')
    titulo = models.CharField('Título',max_length = 225)
    sinopsis = models.TextField('Sinopsis',max_length=200)
    duracion = models.CharField('Duración',max_length=20)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = "Episodio"
        verbose_name_plural = "Episodios"

APICanalLuciernaga/biblioteca/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import Biblioteca, Categoria
from .serializers import BibliotecaSerializer, CategoriaSerializer

# Create your views here.

class BibliotecaViewSet(viewsets.ModelViewSet):
    queryset = Biblioteca.objects.all()
    serializer_class = BibliotecaSerializer 

class CategoriaBibliotecaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer

def Biblioteca_list(request,template='biblioteca.html'):
	b_list = Biblioteca.objects.order_by('-id')
	return render(request,template,locals())

APICanalLuciernaga/templates/biblioteca.html
{% extends "base.html" %}

{% block content %}
<div id="content_hero" style="background-image: url(/static/img/newsbanner.jpg)">
				
	<!-- Content -->
	<div class="container">
		<div class="row blurb scrollme animateme " data-when="exit" data-from="0" data-to="1" data-opacity="0" data-translatey="100">
			<div class="col-md-9">
				<span class="title"></span>
				<p class="banner_det_name bann_name">Biblioteca</p>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Inicio</a></li>
						
						<li class="breadcrumb-item active white-color" aria-current="page">Biblioteca</li>
					</ol>

			</div>
		</div>
	</div>

</div>

<div class="container section">
	<div class="row">
		<div class="col-sm-8 ">
			<ul>
			{% for doc in b_list %}
			<div class="col-md-6 customcard bottom_padd_30">
				<li class="">{{doc}}</li>
				<div>
					<i class="material-icons">
						cloud_download
					</i>
					<a target="_blank" href="/media/{{doc.archivo}}">Descargar</a>
				</div>
			</div>

			{% endfor %}
			</ul>		

		</div>


		<aside class="col-sm-3 col-sm-push-1 sidebar">
			<div class="widget">
				<form>
					<input type="text" placeholder="Buscar..." class="search" />
					<i class="material-icons">search</i>
				</form>
			</div>
			<div class="widget">
				<h3>Temas</h3>
				<ul>

				</ul>
			</div>

			<div class="widget">

			</div>
		</aside>
	</div>
</div>
{% endblock content %}

APICanalLuciernaga/templates/detail_movie.html
{% load thumbnail %}
<section id="activeVideo" class="dark linear-bg hidden">
	<!--<div class=" icon-row " style="position: relative; margin: 10px; z-index: 1; float: right;">
		<div class="col" style="padding-right: 0;">
			<span class=" close_selected">
				<a href="javascript:void(0)">
					<i class="material-icons" onclick="hide_active({{det_vid.id}},{{x.id}})">close</i>
				</a>
			</span>
		</div>

	</div>-->
	<div class="container section remove-bottom-padding">
		<div class="row comingSoon-slides">
			<div class="col-sm-12">		
				<div class="panel with-nav-tabs panel-default cpanel">
					
					<div class="panel-body">
						<div class="tab-content">
							<div class="tab-pane fade" id="tab1default">
								<div class="row single-slide">
									<div class="bg linear-bg" style="background-color: #0f1010;"></div>
									<div class="col-sm-5 col-xs-12 slide-content">
										<span class="title"> {% for cat in det_vid.categoria.all %}
											{{cat}}
											{% if not forloop.last %}-{% endif %}

											{% endfor %}
										</span>
										<h3 class="no-underline">{{det_vid}}</h3>

										<div class="date">
											<i class="material-icons">date_range</i> {{det_vid.fecha|date:"d F"}}, {{det_vid.fecha|date:"Y"}}
											<i class="material-icons" style="margin-left: 5px;">
												av_timer
											</i>{{det_vid.duracion}}

										</div>
										<p>{{det_vid.sinopsis}}</p>
										
										<span class="details">Productora: {{det_vid.produccion}} 
										</span>
										<i class="">
											|
										</i>
										<span class="details">Pais: {{det_vid.pais}}
										</span>
									</div>
									<div class="col-sm-6 col-xs-12 col-sm-push-1 slide-video">
										<a href="https://www.youtube.com/watch?v=0SCvNj9tayk" data-vbtype="video" class="venobox video">
											<i class="material-icons">play_arrow</i>
											{% thumbnail det_vid.imagen "539x307" crop="center" as im%}
											<img src="{{im.url}}" alt="" />
											{% endthumbnail %}
										</a>
									</div>

								</div>

							</div>


							<div class="tab-pane fade" id="tab3default">
								<div class="row">
									<div class="bg linear-bg" style="background: black;">
										
									</div>

									<div class="col-sm-12 col-xs-12">
										<div class="owl-carousel owl-theme">
											{% for sim_vid in y %}
											{% if sim_vid.id != det_vid.id%}
											<div class="item">

												<div>
													<a href="#">
														{% thumbnail sim_vid.imagen "256x340" crop="center" as im %}
														<img src="{{im.url}}" alt="">

														{%empty%}
														<img src="http://via.placeholder.com/265x340" alt="">
														{% endthumbnail%}
													</a>
													<h4 class="left no-underline"> {{sim_vid}}</h4>
												</div>

											</div>

											{% endif %}
											{% endfor %}
										</div>
									</div>
								</div>
							</div>
							
						</div>
					</div>

					<div class="panel-heading no_bottom_border">
						<ul class="nav nav-tabs nav-posit" style="background-color: #000000ab;">
							<li class="active"><a href="#tab1default_{{det_vid.id}}_{{x.id}}" data-toggle="tab">Desripcion</a></li>
							
							<li><a href="#tab3default" data-toggle="tab">Similares</a></li>
						</ul>
					</div>
				</div>


			</div>
		</div>
	</div>
</section>

APICanalLuciernaga/templates/en_vivo.html
{% extends "base.html" %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block content %}

{% for directo in v_directo|slice:"1" %}
<div class=" section" style="margin-top:100px;">

		
	
	<div class="row">
		<div class="col-sm-12">

		
			

			<div style="text-align:center">			


				<iframe width="100%" height="600" src="{{directo.link}}?modestbranding=1&autoplay=1&controls=1&fs=0&loop=1&rel=0&showinfo=0&disablekb=1&mute=1" allowfullscreen allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" frameborder="0">
				</iframe>

			
			</div>

			<div class="buttons text-center top_padd_30">

				<a href="#inline-content" class="venobox btn btn-default" data-vbtype="inline">

					<span>Programación</span>
				</a>
			</div>

		</div>
	</div>

	<div id="inline-content" style="display:none;">
		<div class="padd_15">
			<div class="col-sm-12">
				<div class="tabs movies">
					<ul>
						<li><a class="text-center" href="#wed">Programación</a></li>
						<li class="date"><span class="">{{fecha_hoy}}</span></li>
					</ul>
				</div>

				<div class="table-responsive">

				<table class="table table-dark">
					<tbody>
						{% for programa  in directo.horaprogramacion_set.all %}
							
						
						<tr>
							<th scope="row" style="vertical-align: middle;">
								<span class="time past"style="background-color: gray; border-radius: 5px;padding: 5px;color: antiquewhite;">{{programa.hora_inicio|time:"TIME_FORMAT"}}</span> 
								<span class="time"style="background-color: gray;border-radius: 5px;padding: 5px;color: white;">{{programa.hora_fin|time:"TIME_FORMAT"}}</span>	
							</th>
							<td>
								<h3 class="no-underline white-color">
									<span class="title">{{programa.titulo}}</span>
								</h3>
								{% if programa.descripcion %}
									<p>{{programa.descripcion}}</p>
								{% endif %}
								
								<span class="white-color">Nicaragua</span>
							</td>
							<td style="vertical-align: middle;">
								<p>Economia</p> 
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				</div>
			</div>
		</div>
	</div>


	

</div>

{% endfor %}	
{% endblock content %}

APICanalLuciernaga/templates/movies.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
<div id="content_hero" style="background-image: url(/static/img/movie-main_banner.jpg)">

	<!-- <img src="images/scroll-arrow.svg" alt="Scroll down" class="scroll" /> -->

	<!-- Content -->
	<div class="container">
		<div class="row blurb scrollme animateme " data-when="exit" data-from="0" data-to="1" data-opacity="0" data-translatey="100">
			<div class="col-md-9">
				<span class="title"></span>
				<h1>
					{% if request.path == '/videos/documentales/' %}
						Documentales
						{% endif %}
						{% if request.path == '/videos/series/' %}
						Series
						{% endif %}
						{% if request.path == '/videos/peliculas/' %}
						Peliculas
						{% endif %}
				</h1>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="/">Inicio</a></li>
					<li class="breadcrumb-item active white-color" aria-current="page">
						{% if request.path == '/videos/documentales/' %}
						Documentales
						{% endif %}
						{% if request.path == '/videos/series/' %}
						Series
						{% endif %}
						{% if request.path == '/videos/peliculas/' %}
						Peliculas
						{% endif %}
				</li>
				</ol>

			</div>
		</div>
	</div>

</div>

{% for x,y in movies_by_cat.items %}

<div class="container section {% if not forloop.last %}rm_padd_bottom{% endif %}">
	<div class="row">
		<div class="col-sm-12" id="afterHeader">
			<h2>{{x}}</h2>
			
			<div class="slick-carousel" id="cat-{{x.id}}">
				{% for video in  y %}
				<div class="movie-slide">
					<div class="movie-poster">
						<aside>
							<div>
								<a href="" class="venobox play">
									<i class="material-icons">play_arrow</i>
								</a>
								<div style="padding-top: 15px;">
									<span class="date">
										{% for cat in video.categoria.all|slice:"3" %}
										{{cat}} 
										{% if not forloop.last %},{% endif %}
										{% endfor%}									
									</span>

									<span class="date"><strong>{{video}} </strong> </span>											
									<p id="expand-action" onclick="showmore({{video.id}},{{x.id}})">
										<i class="material-icons expand-more">
											expand_more
										</i>
									</p>
								</div>
							</div>
						</aside>
						<a href="#">
							{% thumbnail video.imagen "270x337" crop="center" as im %}
							<img src="{{ im.url }}" alt="">
							{% empty %}
							<img src="http://via.placeholder.com/270x337" alt="">
							{% endthumbnail %}
						</a>
					</div>
					<!--<span class="title genrecolor">Ficcion</span> -->
					<h4 id="video_name_{{video.id}}_{{x.id}}" class="no-underline white-color hg_video">
					{{video|striptags|truncatechars:29}}
					</h4> 
					<a id="expand-icon_{{video.id}}_{{x.id}}" href="" class="hidden">
						<i class="material-icons" style="font-size: 32px;">
							expand_more
						</i>
					</a>

				</div>
				{% endfor %}
			</div>
			
		</div>
	</div>
</div>

{% for det_vid in  y %}

<section id="activeVideo_{{det_vid.id}}_{{x.id}}" class="dark linear-bg hidden">
	<div class=" icon-row " style="position: relative; margin: 10px; z-index: 1; float: right;">
		<div class="col" style="padding-right: 0;">
			<span class=" close_selected">
				<a href="javascript:void(0)">
					<i class="material-icons" onclick="hide_active({{det_vid.id}},{{x.id}})">close</i>
				</a>
			</span>
		</div>

	</div>
	<div class="container section remove-bottom-padding">
		<div class="row comingSoon-slides">
			<div class="col-sm-12">

				<div class="row">
					<div class="bg linear-bg" style="background-color: #0f1010;"></div>
					<div class="col-sm-5 col-xs-12 slide-content">
						<span class="title"> {% for cat in det_vid.categoria.all %}
							{{cat}}
							{% if not forloop.last %}-{% endif %}

							{% endfor %}
						</span>
						<h3 class="no-underline">{{det_vid}}</h3>

						<div class="date">
							<i class="material-icons">date_range</i> {{det_vid.fecha|date:"d F"}}, {{det_vid.fecha|date:"Y"}}
							<i class="material-icons" style="margin-left: 5px;">
								av_timer
							</i>{{det_vid.duracion}}

						</div>
						<p>{{det_vid.sinopsis}}</p>

						<span class="details">Productora: {{det_vid.produccion}} 
						</span>
						<i class="">
							|
						</i>
						<span class="details">Pais: {{det_vid.pais}}
						</span>
					</div>
					<div class="col-sm-6 col-xs-12 col-sm-push-1 slide-video">
						<a href="https://www.youtube.com/watch?v=0SCvNj9tayk" data-vbtype="video" class="venobox video">
							<i class="material-icons">play_arrow</i>
							{% thumbnail det_vid.imagen "539x307" crop="center" as im%}
							<img src="{{im.url}}" alt="" />
							{% endthumbnail %}
						</a>
					</div>

				</div>

				<div class="row">
					<div class="bg linear-bg" style="background: black;">

					</div>

					<div class="col-sm-12 col-xs-12">
						<div class="owl-carousel owl-theme">
							{% for sim_vid in y|slice:"16" %}
							{% if sim_vid.id != det_vid.id%}
							<div class="item">

								<div>
									<a href="#">
										{% thumbnail sim_vid.imagen "256x340" crop="center" as im %}
										<img src="{{im.url}}" alt="">

										{%empty%}
										<img src="http://via.placeholder.com/265x340" alt="">
										{% endthumbnail%}
									</a>
									<h4 class="left no-underline"> {{sim_vid}}</h4>
								</div>

							</div>

							{% endif %}
							{% endfor %}
						</div>
					</div>
				</div>

				{% if is_serie %}
					<div class="row">
					<div class="bg linear-bg" style="background: black;"></div>
					<div class="col-sm-12 col-xs-12 slide-content">
						<!-- dropdown inline de temporada y cap -->
						<div>
							<div class="d-inline-block">
								<div class="dropdown show">
									<a class="btn btn-secondary dropdown-toggle light_hover" href="#" role="button" id="dropdownSeason" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Temporada
										<i class="material-icons">arrow_drop_down</i>
									</a>

									<div class="dropdown-menu" aria-labelledby="dropdownSeason">
										<a class="dropdown-item active" href="#">1</a>
										<a class="dropdown-item" href="#">2</a>
										<a class="dropdown-item" href="#">3</a>
									</div>
								</div>
							</div>

							<div class="d-inline-block">

								<div class="dropdown show">
									<a class="btn btn-secondary dropdown-toggle light_hover" href="#" role="button" id="dropdownSeason" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Episodio <i class="material-icons">arrow_drop_down</i>
									</a>

									<div class="dropdown-menu" aria-labelledby="dropdownSeason">
										<a class="dropdown-item active" href="#">1</a>
										<a class="dropdown-item" href="#">2</a>
										<a class="dropdown-item" href="#">3</a>
									</div>
								</div>
							</div>
						</div>

						{% for temp in det_vid.temporada_set.all %}
							
								<h1>Temporada {{temp.id}}</h1>
								<div class="owl-carousel owl-theme">
									{% for ep in temp.episodio_set.all %}

									<div class="item">
										<div>
											
											<a href="#">
												{% thumbnail ep.imagen "256x340" crop="center" as im %}
												<img src="{{im.url}}" alt="">

												{%empty%}
												<img src="http://via.placeholder.com/265x340" alt="">
												{% endthumbnail%}
											</a>
											<h4 class="left no-underline"> {{ep}}</h4>
										</div>

									</div>
									{% endfor %}
								</div>
							
						{% endfor %}


					</div>
					<!-- Capitulos -->

				</div>
				{% endif %}

				




			<!--
				Panel con los tabs
				<div class="panel with-nav-tabs panel-default cpanel">
					
					<div class="panel-body">
						<div class="tab-content">
							<div class="tab-pane fade" id="tab1default_{{det_vid.id}}_{{x.id}}">
								<div class="row single-slide">
									<div class="bg linear-bg" style="background-color: #0f1010;"></div>
									<div class="col-sm-5 col-xs-12 slide-content">
										<span class="title"> {% for cat in det_vid.categoria.all %}
											{{cat}}
											{% if not forloop.last %}-{% endif %}

										{% endfor %}
										</span>
										<h3 class="no-underline">{{det_vid}}</h3>

										<div class="date">
											<i class="material-icons">date_range</i> {{det_vid.fecha|date:"d F"}}, {{det_vid.fecha|date:"Y"}}
											<i class="material-icons" style="margin-left: 5px;">
												av_timer
											</i>{{det_vid.duracion}}

										</div>
										<p>{{det_vid.sinopsis}}</p>
										
										<span class="details">Productora: {{det_vid.produccion}} 
										</span>
										<i class="">
											|
										</i>
										<span class="details">Pais: {{det_vid.pais}}
										</span>
									</div>
									<div class="col-sm-6 col-xs-12 col-sm-push-1 slide-video">
										<a href="https://www.youtube.com/watch?v=0SCvNj9tayk" data-vbtype="video" class="venobox video">
											<i class="material-icons">play_arrow</i>
											{% thumbnail det_vid.imagen "539x307" crop="center" as im%}
											<img src="{{im.url}}" alt="" />
											{% endthumbnail %}
										</a>
									</div>

								</div>

							</div>


							<div class="tab-pane fade" id="tab3default_{{det_vid.id}}_{{x.id}}">
								<div class="row">
									<div class="bg linear-bg" style="background: black;">
										
									</div>

									<div class="col-sm-12 col-xs-12">
										<div class="owl-carousel owl-theme">
											{% for sim_vid in y|slice:"16" %}
												{% if sim_vid.id != det_vid.id%}
										    	<div class="item">
										    	
												<div>
													<a href="#">
														{% thumbnail sim_vid.imagen "256x340" crop="center" as im %}
														<img src="{{im.url}}" alt="">

														{%empty%}
														<img src="http://via.placeholder.com/265x340" alt="">
														{% endthumbnail%}
													</a>
													<h4 class="left no-underline"> {{sim_vid}}</h4>
												</div>
										    	
										    </div>

											{% endif %}
											{% endfor %}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="panel-heading no_bottom_border">
						<ul class="nav nav-tabs nav-posit" style="background-color: #000000ab;">
							<li id="activelitab_{{det_vid.id}}_{{x.id}}"><a href="#tab1default_{{det_vid.id}}_{{x.id}}" data-toggle="tab">Desripcion</a></li>
							
							<li><a href="#tab3default_{{det_vid.id}}_{{x.id}}" data-toggle="tab">Similares</a></li>
						</ul>
					</div>
				</div>

			-->


			</div>
		</div>
	</div>
</section>

{% endfor %}

{% endfor %}<!-- fin for loop videos por categoria -->


{% endblock content %}

{% block extra_js %}
<script>

jQuery(function ($) {

	$(window).on('load resize scroll', function(){ 
		{% for x,y in movies_by_cat.items %}
		$('#cat-{{x.id}}').not('.slick-initialized').slick({
			autoplay: false,
			autoplaySpeed: 3000,
			slidesToShow: 4,
			centerPadding: '60px',
			prevArrow: '<i class="material-icons left">keyboard_arrow_left</i>',
			nextArrow: '<i class="material-icons right">keyboard_arrow_right</i>',
			responsive: [
			    {
			      breakpoint: 768,
			      settings: {
			        slidesToShow: 2
			      }
			    },
			    {
			      breakpoint: 480,
			      settings: {
			        slidesToShow: 1
			      }
			    }
			  ]
		});

		{% endfor %}
						
	});
});

$('.owl-carousel').owlCarousel({
    stagePadding: 50,
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
});
</script>
{% endblock extra_js %}